apiVersion: v1
kind: PersistentVolume
metadata:
  name: myvolume
spec:
  hostPath:
    path: /etc/foo
  storageClassName: normal
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
