apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: logger
  name: logger
spec:
  volumes:
    - name: pod-storage
      persistentVolumeClaim:
        claimName: log-claim
  containers:
  - image: nginx
    name: logger
    resources: {}
    volumeMounts:
      - mountPath: "/var/www/nginx"
        name: pod-storage
  restartPolicy: Always
status: {}
