apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        resources: {}
        volumeMounts:
        - mountPath: /redis-master-data
          name: data
        - mountPath: /redis-master
          name: redis-config
        ports:
          - containerPorts: 6379
  volumes:
  - name: data
    emptyDir:
      sizeLimit: 500Mi
  - name: redis-config
    configMap:
      name: log-config
      items:
        - key: log_level
          path: log_level.conf
status: {}
