apiVersion: v1
kind: Pod
metadata:
    name: time-check
spec:
  containers:
  - command: ["/bin/bash", "-c" "while true; do date; sleep $TIME_FREQ;done"]
    image: busybox
    name: time-check
    env:
      - name: TIME_FREQ
        valueFrom:
          configMapKeyRef:
            name: time-config
            key: TIME_FREQ
    volumeMounts:
    - name: opt-vol
      mountPath: /opt/time
  volumes:
  - name: opt-vol
    hostPath:
      path: /opt/time # directory location on host
  restartPolicy: Always
status: {}
